name: Deploy CloudOps App

on:
  push:
    branches:
      - main
      - feature/cloudwatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Deploy Backend (Terraform)
        run: |
          cd backend
          terraform init
          terraform apply -auto-approve

      - name: Deploy Frontend (S3)
        run: |
          cd frontend
          aws s3 sync . s3://aws-cloudops-app-frontend --delete
